<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ideas )</name>
   <tag></tag>
   <elementGuidId>d664d70d-eed8-4846-ba5d-5eefe6cc959f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='commThemeNav']/div/div/nav/ul/li[8]/div/div[2]/div/ul/li[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;ideas :)&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>85f82d0b-50b8-4f04-91d3-fb972a9bed83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>958:0</value>
      <webElementGuid>e418d0cf-8048-4f08-bf89-71958007876f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/katalonhelpcenter/s/ideas</value>
      <webElementGuid>81fd9bb4-954d-46e2-bda4-95b3ca15996b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>80fe3cf2-b618-4a1c-bf3c-c539ef331418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7233b906-1ac8-4c91-8923-318620c9c202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e4b9f1e2-c508-448e-9a1e-ec9f3f8b9395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>ideas :)</value>
      <webElementGuid>543f2759-b800-4da2-9287-bf076d3fd185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-special-link</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b0dca055-86d6-439b-a3ec-a070787bdbd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ideas :)</value>
      <webElementGuid>3dd0d7e7-24ed-47b8-b608-ed40e47d8c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;commThemeNav&quot;)/div[1]/div[@class=&quot;ui-widget&quot;]/nav[@class=&quot;jepsonInnerHeader commThemeCmp comm-navigation themeNavContainer navMenuType-expanded alignPanel-left forceCommunityThemeNav doneRendering&quot;]/ul[@class=&quot;visible-links themeNav-align-left&quot;]/li[@class=&quot;comm-navigation__top-level-item comm-navigation__menu-item&quot;]/div[@class=&quot;mainNavItem hasSubNav themeNavMoreLink uiMenu expanded&quot;]/div[@class=&quot;subMenu slds-nubbin_top-left popupTargetContainer uiPopupTarget uiMenuList uiMenuList--default visible positioned&quot;]/div[@class=&quot;subMenu slds-nubbin_top-left&quot;]/ul[@class=&quot;scrollable&quot;]/li[@class=&quot;comm-navigation__menu-item comm-navigation__sub-menu-item subMenuItem js-menu-item finalSubMenuItem uiMenuItem&quot;]/a[1]</value>
      <webElementGuid>27dc23ad-7808-404e-a700-bf3a377fdb64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='commThemeNav']/div/div/nav/ul/li[8]/div/div[2]/div/ul/li[5]/a</value>
      <webElementGuid>b232a712-55af-4b48-8fd3-f05b1235f553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'ideas :)')])[2]</value>
      <webElementGuid>4bd1629f-4a18-4b87-967d-31fe042932e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Live Chat'])[2]/following::a[1]</value>
      <webElementGuid>994f4f19-0495-4905-bef6-af5b6f1f1735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Best Practice'])[2]/following::a[2]</value>
      <webElementGuid>983ffb60-e4dc-4934-a081-c00fc3eb37f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expand search'])[1]/preceding::a[1]</value>
      <webElementGuid>08d8e626-7c03-4029-b694-79a27e8b477d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::a[1]</value>
      <webElementGuid>830820b3-e370-485b-a8da-129c7f2338d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/katalonhelpcenter/s/ideas')])[2]</value>
      <webElementGuid>5880a3a0-c18a-4746-82c3-e65f486ff269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[5]/a</value>
      <webElementGuid>b4f9d2db-b28a-4013-afdd-4d3e21ee1f94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/katalonhelpcenter/s/ideas' and @title = 'ideas :)' and (text() = 'ideas :)' or . = 'ideas :)')]</value>
      <webElementGuid>809b43eb-ffe7-4333-8fb5-341361c5f489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='commThemeNav']/div/div/nav/ul/li[8]/div/div[2]/div/ul/li[4]/a</value>
      <webElementGuid>fbab77c4-2665-4d19-aa8a-3e2274b94662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[4]/a</value>
      <webElementGuid>783b68bb-9b43-4570-b51c-49cdb343e626</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
