<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ideas ) (1)</name>
   <tag></tag>
   <elementGuidId>3eeea05f-18fd-4013-ace3-4dc26d67f2db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='commThemeNav']/div/div/nav/ul/li[8]/div/div[2]/div/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;ideas :)&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4d221846-de42-4832-aa00-1b8e7df757b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>942:0</value>
      <webElementGuid>2aa04465-cfc4-4e43-834f-9ebe3bab2119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/katalonhelpcenter/s/ideas</value>
      <webElementGuid>169943f5-4b12-4f4d-ac1e-b78d6740e5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>256d88c0-233a-4bb3-8f2e-91451461bf35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ced5c181-418a-469c-a2f9-5a052d7f7cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e0daad50-7ef5-4e7e-b730-27874c51c8ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>ideas :)</value>
      <webElementGuid>845330ba-521d-413a-a88c-8052fc6b686d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-special-link</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1988f6c4-e13f-47ca-8779-9e9b60f83be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ideas :)</value>
      <webElementGuid>41bdb780-dcf4-43d1-a709-4790dc462edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;commThemeNav&quot;)/div[1]/div[@class=&quot;ui-widget&quot;]/nav[@class=&quot;jepsonInnerHeader commThemeCmp comm-navigation themeNavContainer navMenuType-expanded alignPanel-left forceCommunityThemeNav doneRendering&quot;]/ul[@class=&quot;visible-links themeNav-align-left&quot;]/li[@class=&quot;comm-navigation__top-level-item comm-navigation__menu-item&quot;]/div[@class=&quot;mainNavItem hasSubNav themeNavMoreLink uiMenu expanded&quot;]/div[@class=&quot;subMenu slds-nubbin_top-left popupTargetContainer uiPopupTarget uiMenuList uiMenuList--default visible positioned&quot;]/div[@class=&quot;subMenu slds-nubbin_top-left&quot;]/ul[@class=&quot;scrollable&quot;]/li[@class=&quot;comm-navigation__menu-item comm-navigation__sub-menu-item subMenuItem js-menu-item finalSubMenuItem uiMenuItem&quot;]/a[1]</value>
      <webElementGuid>cf38ad2a-d4fa-40a8-8bf0-7c2d7d72100d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='commThemeNav']/div/div/nav/ul/li[8]/div/div[2]/div/ul/li[4]/a</value>
      <webElementGuid>424da113-8a80-40fc-a9d9-4ee9d8ed0459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'ideas :)')])[2]</value>
      <webElementGuid>68741e0b-b84d-4eb4-9480-16877069557c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Live Chat'])[2]/following::a[1]</value>
      <webElementGuid>bc54a1ef-ed2e-4011-817e-7a80d03ead05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Best Practice'])[2]/following::a[2]</value>
      <webElementGuid>ad584a6f-2878-426f-9b96-1e846b8ea9dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expand search'])[1]/preceding::a[1]</value>
      <webElementGuid>da3e22f3-15cb-491a-bf72-7741822905cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::a[1]</value>
      <webElementGuid>d0e1af59-ea61-4f2c-a947-a950c0fdff36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/katalonhelpcenter/s/ideas')])[2]</value>
      <webElementGuid>df6e53bf-58ce-4de9-bcfb-03b3abc02fa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[4]/a</value>
      <webElementGuid>995dc8e2-8153-401c-931a-a6ef2ad48b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/katalonhelpcenter/s/ideas' and @title = 'ideas :)' and (text() = 'ideas :)' or . = 'ideas :)')]</value>
      <webElementGuid>28cf41f7-5120-4a09-b9ce-8021aece8e99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
