<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Upvote</name>
   <tag></tag>
   <elementGuidId>8adf1b6d-1e96-4d17-9dbf-b8bc1bb9fd53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Question 4'])[1]/following::button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.slds-button.slds-button_neutral</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9612f5bb-2aa7-4a3a-b12d-25e4ee9bb2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-button slds-button_neutral</value>
      <webElementGuid>8482d33b-2427-445e-b9c6-6aa33bb84591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon-name</name>
      <type>Main</type>
      <value>utility:like</value>
      <webElementGuid>69f80d49-4d58-4ab5-bc0f-d756abb131b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upvote</value>
      <webElementGuid>8d15be26-03fb-4096-813b-f3bba59ac845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;null comm-page-detail-a4D&quot;]/div[@class=&quot;themeLayoutStarterWrapper isHeroUnderHeader-false isHeaderPinned-false siteforceThemeLayoutStarter&quot;]/div[@class=&quot;body isPageWidthFixed-true&quot;]/div[@class=&quot;siteforceSldsTwoCol84Layout siteforceContentArea&quot;]/div[@class=&quot;slds-grid slds-wrap slds-medium-nowrap slds-large-nowrap&quot;]/div[@class=&quot;slds-col--padded slds-size--12-of-12 slds-medium-size--4-of-12 slds-large-size--4-of-12 comm-layout-column&quot;]/div[1]/div[@class=&quot;ui-widget&quot;]/c-vote-idea-l-w-c[1]/div[@class=&quot;voteIdeaCss&quot;]/div[@class=&quot;slds-grid slds-wrap&quot;]/div[@class=&quot;slds-size_10-of-12&quot;]/div[@class=&quot;slds-box slds-box_x-small slds-text-align_center slds-m-around_x-small&quot;]/div[1]/button[@class=&quot;slds-button slds-button_neutral&quot;]</value>
      <webElementGuid>c882585f-6a47-46df-bb62-e702e79b5679</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Question 4'])[1]/following::button[1]</value>
      <webElementGuid>c0b68e30-a792-4f01-9e37-2074c8e32a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Are there any other relevant details or specifications that you', &quot;'&quot;, 'd like to add?')])[1]/following::button[1]</value>
      <webElementGuid>0b86814a-092d-4f3e-9d2c-c2c237b8b30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created on 2023-08-26'])[1]/preceding::button[2]</value>
      <webElementGuid>424c811f-4a6e-40cf-845c-24b27339e82b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submitted'])[2]/preceding::button[4]</value>
      <webElementGuid>79638cc4-aab3-44e3-9f9c-67252a57f3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Upvote']/parent::*</value>
      <webElementGuid>a5ba411e-5f73-4662-9031-f4d1869656e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//c-vote-idea-l-w-c/div/div/div[2]/div/div/button</value>
      <webElementGuid>2d30187e-bf53-4a5f-82de-9518dfc8c821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Upvote' or . = 'Upvote')]</value>
      <webElementGuid>93ba7276-8f21-464f-bde2-6096472a57a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
