<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Post Idea</name>
   <tag></tag>
   <elementGuidId>515ce1f3-a730-4228-a3cc-4d308ee11b05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[39]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.slds-button.slds-button_brand</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>def755be-c549-4474-b821-18395382268b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-button slds-button_brand</value>
      <webElementGuid>29c58e6a-cda3-4507-8119-a557e971278f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6b191074-2a52-408a-83c1-ffb335e13baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8b9a840c-8d4b-4d27-a823-d3dc0f5a87d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Post Idea</value>
      <webElementGuid>acdc6d7e-71bd-4635-9864-750c16c96e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;534:0&quot;)/div[1]/div[@class=&quot;ui-widget&quot;]/c-k-i_-post-idea-l-w-c[1]/div[@class=&quot;slds-grid slds-gutters&quot;]/div[@class=&quot;slds-col slds-size_2-of-3&quot;]/lightning-card[1]/article[@class=&quot;slds-card&quot;]/div[@class=&quot;slds-card__body&quot;]/slot[1]/div[@class=&quot;slds-col slds-size_12-of-12&quot;]/div[@class=&quot;slds-clearfix&quot;]/lightning-button[@class=&quot;slds-align_absolute-center&quot;]/button[@class=&quot;slds-button slds-button_brand&quot;]</value>
      <webElementGuid>a4cd2544-9f8e-49d0-ae52-7c5998bde53d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[39]</value>
      <webElementGuid>469a88de-d8a5-4211-9374-57320fc47a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='534:0']/div/div[2]/c-k-i_-post-idea-l-w-c/div/div/lightning-card/article/div[2]/slot/div/div[9]/lightning-button/button</value>
      <webElementGuid>ce7035b2-f142-4650-9e1d-612556f6f66c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove formatting'])[2]/following::button[1]</value>
      <webElementGuid>81359f02-e643-4236-a36c-9af4cee9cae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Image'])[2]/following::button[2]</value>
      <webElementGuid>b68a19fa-f42c-4e13-a451-61c3a972c2f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find what you need here.'])[1]/preceding::button[1]</value>
      <webElementGuid>d9f24f33-8e75-4d8b-b496-e7cd44b68f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Navigation Mode'])[1]/preceding::button[1]</value>
      <webElementGuid>be64f3ba-395e-4ed6-a22b-eae3fbcb755f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-button/button</value>
      <webElementGuid>da0f06a0-6ccc-4b3f-abe5-ab4cc820bd71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Post Idea' or . = 'Post Idea')]</value>
      <webElementGuid>5cfc87d8-dd1e-4260-bb28-5d2d3f961ae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='824:0']/div/div[2]/c-k-i_-post-idea-l-w-c/div/div/lightning-card/article/div[2]/slot/div/div[9]/lightning-button/button</value>
      <webElementGuid>aa48f0eb-37b5-4981-a16d-51f503236865</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
