<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Enter</name>
   <tag></tag>
   <elementGuidId>dfc13212-68a0-46ca-91f0-b79bf79e0192</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='824:0']/div/div[2]/c-k-i_-post-idea-l-w-c/div/div/lightning-card/article/div[2]/slot/div/div[7]/lightning-input-rich-text/div/div/div/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.slds-rich-text-area__content.slds-grow.slds-text-color-weak.standin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f50d1c26-3123-4036-86a7-4c2229df6d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-rich-text-area__content slds-grow slds-text-color-weak standin</value>
      <webElementGuid>d8836205-7408-4123-9819-4272825c903e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enter...</value>
      <webElementGuid>6f649b38-3d1f-4b53-a167-c79e37f2180e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;824:0&quot;)/div[1]/div[@class=&quot;ui-widget&quot;]/c-k-i_-post-idea-l-w-c[1]/div[@class=&quot;slds-grid slds-gutters&quot;]/div[@class=&quot;slds-col slds-size_2-of-3&quot;]/lightning-card[1]/article[@class=&quot;slds-card&quot;]/div[@class=&quot;slds-card__body&quot;]/slot[1]/div[@class=&quot;slds-col slds-size_12-of-12&quot;]/div[7]/lightning-input-rich-text[@class=&quot;slds-form-element&quot;]/div[1]/div[@class=&quot;slds-form-element__control&quot;]/div[@class=&quot;slds-rich-text-editor slds-grid slds-grid_vertical slds-nowrap&quot;]/div[@class=&quot;slds-rich-text-editor__textarea slds-grid&quot;]/div[@class=&quot;slds-rich-text-area__content slds-grow slds-text-color-weak standin&quot;]</value>
      <webElementGuid>845b950c-1692-4f4f-81a0-9920b870f812</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='824:0']/div/div[2]/c-k-i_-post-idea-l-w-c/div/div/lightning-card/article/div[2]/slot/div/div[7]/lightning-input-rich-text/div/div/div/div[3]/div</value>
      <webElementGuid>65d81e63-3aca-462a-85f2-2f28c0b7fd55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove formatting'])[1]/following::div[3]</value>
      <webElementGuid>4479c587-60cb-481d-be44-aa3533320453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Image'])[1]/following::div[3]</value>
      <webElementGuid>7c8da308-8789-4848-af4b-2561f4c6b7c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Font'])[2]/preceding::div[1]</value>
      <webElementGuid>db3c584a-7548-4fd7-b52d-09458174246b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salesforce Sans'])[2]/preceding::div[1]</value>
      <webElementGuid>e2970d46-23ab-4983-883e-f99f081a6d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-input-rich-text/div/div/div/div[3]/div</value>
      <webElementGuid>4abdefbc-c404-41c8-a010-9d8da2ba33e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Enter...' or . = 'Enter...')]</value>
      <webElementGuid>99084a91-13bb-4ce0-89e0-93e7359f6322</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
