<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Title</name>
   <tag></tag>
   <elementGuidId>b1c4b9ac-8aa5-4364-b2bd-b8c2525b6644</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-14']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-14</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f06a637-d9c6-42a9-828f-0bd2dbc9c93d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>f1f249a4-c9b3-4af8-814d-2ac99c4a1b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9d888e13-4717-40bf-8286-f68ed8d902e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-14</value>
      <webElementGuid>2e625f57-6117-4157-b93d-83a93cbef551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ceab284-4216-48f6-afb5-3ce54c1db00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>help-message-14</value>
      <webElementGuid>56d43c04-2dba-40ab-a9cf-28c6e45c0f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>05cced7c-d5c8-4039-8778-b904a321c8fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>e0b9ecf7-1a05-4de9-ae80-b8034ab3d96f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Title</value>
      <webElementGuid>fab7667a-44fe-4484-9e73-c0709f4bee1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>2ddab9d5-02e7-4132-afe5-b1ba7c22c3ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-14&quot;)</value>
      <webElementGuid>bd950886-9fe5-4c8c-a66f-0b6dc0cb2a59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-14']</value>
      <webElementGuid>827d2680-99fb-43e6-a73b-a8bb86f32240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='534:0']/div/div[2]/c-k-i_-post-idea-l-w-c/div/div/lightning-card/article/div[2]/slot/div/div/lightning-input/div/div/input</value>
      <webElementGuid>3cc56058-ff63-4734-8a01-39f134723020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-input/div/div/input</value>
      <webElementGuid>1ec30399-8a5e-46c1-a757-61fee6a0cc31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-14' and @placeholder = 'Enter Title' and @name = 'Title']</value>
      <webElementGuid>046c4132-c8ba-4ea0-ab9c-34a274496306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-44']</value>
      <webElementGuid>337673a1-991d-4396-b5a0-c8737f6ceda0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='824:0']/div/div[2]/c-k-i_-post-idea-l-w-c/div/div/lightning-card/article/div[2]/slot/div/div/lightning-input/div/div/input</value>
      <webElementGuid>d0f19588-57a7-4408-a188-e21ea9f06de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input-44' and @placeholder = 'Enter Title' and @name = 'Title']</value>
      <webElementGuid>370b2157-c4c5-4171-bde6-1e900214cb5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
