<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lightning-combobox_Product</name>
   <tag></tag>
   <elementGuidId>db414bbc-fd94-4085-830c-1341c7267bb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='824:0']/div/div[2]/c-k-i_-post-idea-l-w-c/div/div/lightning-card/article/div[2]/slot/div/div[2]/lightning-combobox</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>lightning-combobox.slds-form-element</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lightning-combobox</value>
      <webElementGuid>bebe4336-c752-4d16-b864-807bcedf3249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-form-element</value>
      <webElementGuid>a212ef54-2c66-4cb8-ab78-3aee3647efc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>*Product</value>
      <webElementGuid>b1711630-bc2c-480f-852b-352e1c368004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;824:0&quot;)/div[1]/div[@class=&quot;ui-widget&quot;]/c-k-i_-post-idea-l-w-c[1]/div[@class=&quot;slds-grid slds-gutters&quot;]/div[@class=&quot;slds-col slds-size_2-of-3&quot;]/lightning-card[1]/article[@class=&quot;slds-card&quot;]/div[@class=&quot;slds-card__body&quot;]/slot[1]/div[@class=&quot;slds-col slds-size_12-of-12&quot;]/div[2]/lightning-combobox[@class=&quot;slds-form-element&quot;]</value>
      <webElementGuid>6dd1840a-7ee2-4e47-8c97-3ba363f73ced</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='824:0']/div/div[2]/c-k-i_-post-idea-l-w-c/div/div/lightning-card/article/div[2]/slot/div/div[2]/lightning-combobox</value>
      <webElementGuid>73951e49-1d7d-4001-be94-767900eb49bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimum of 10 characters required'])[1]/following::lightning-combobox[1]</value>
      <webElementGuid>6050285b-cd9f-47d6-89cc-d6f2c537679b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::lightning-combobox[1]</value>
      <webElementGuid>77356f57-1dac-48b9-9245-f5ad686eeaea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-combobox</value>
      <webElementGuid>4cc0aea4-6da1-4877-86fc-bb9ddc0fa428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//lightning-combobox[(text() = '*Product' or . = '*Product')]</value>
      <webElementGuid>9ce76c72-5afd-46da-bbc8-672ac94c6ab5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
