<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Please log in with your Enterprise licens_4c9434</name>
   <tag></tag>
   <elementGuidId>e105ce76-19f0-4e64-8ea5-e41194a7639c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='428:0']/div/div[2]/c-k-i_-post-idea-l-w-c/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.bg > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>bca9740a-cc09-480d-8de7-c208fdd54038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please log in with your Enterprise licensed account to post your ideas</value>
      <webElementGuid>2c6725e7-7a12-4a06-a194-e91a0cbe4325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;428:0&quot;)/div[1]/div[@class=&quot;ui-widget&quot;]/c-k-i_-post-idea-l-w-c[1]/div[@class=&quot;bg&quot;]/p[1]</value>
      <webElementGuid>d015085e-d341-48b3-ae9c-06707347344d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='428:0']/div/div[2]/c-k-i_-post-idea-l-w-c/div/p</value>
      <webElementGuid>68034b6e-6152-4c08-839c-6f6e0c580e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View All'])[1]/following::p[2]</value>
      <webElementGuid>2f6ba2df-0820-4408-bc04-3f5d66f7503e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rule of engagement in ideaExchange board'])[1]/following::p[2]</value>
      <webElementGuid>06921640-f6fb-42c7-9d03-aff7e61c02af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading'])[2]/preceding::p[1]</value>
      <webElementGuid>524eeac4-83cc-420c-9b48-d9eff57d0efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please']/parent::*</value>
      <webElementGuid>ed3acb2f-cac9-44b5-884b-7ff5b3fc5fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//c-k-i_-post-idea-l-w-c/div/p</value>
      <webElementGuid>f6ea1c0e-29f9-49e7-a725-6fb01bec6fa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Please log in with your Enterprise licensed account to post your ideas' or . = 'Please log in with your Enterprise licensed account to post your ideas')]</value>
      <webElementGuid>5ced24a0-3f6b-4575-afa2-724f9113daa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
