<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cloud Studio</name>
   <tag></tag>
   <elementGuidId>d2caabe4-d044-4617-8562-5120b0fbf5ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//lightning-base-combobox-item[@id='combobox-button-16-2-16']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#combobox-button-16-2-16 > span.slds-media__body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>042a47ca-de17-4aeb-810b-634a15636d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-media__body</value>
      <webElementGuid>e3b4b6c1-0bf7-4783-81c1-c0a38aa023ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cloud Studio</value>
      <webElementGuid>abc4a101-d2a5-45ad-8793-ab3dabada62a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combobox-button-16-2-16&quot;)/span[@class=&quot;slds-media__body&quot;]</value>
      <webElementGuid>95501fc4-6b09-4e92-8f79-23e5764985fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-button-16-2-16']/span[2]</value>
      <webElementGuid>9038ead5-782b-4414-8f07-2562dce8f775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Studio'])[1]/following::span[2]</value>
      <webElementGuid>276e3fec-83f1-47b4-9651-60710cb9895b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Product'])[1]/following::span[5]</value>
      <webElementGuid>09b86943-356b-402f-b620-94be55af28c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TestOps'])[1]/preceding::span[3]</value>
      <webElementGuid>c1e14961-cee4-474b-9d2b-7c0c9661cc54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[3]/span[2]</value>
      <webElementGuid>857d5a15-84cd-451c-97e4-0d0bde00d354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Cloud Studio' or . = 'Cloud Studio')]</value>
      <webElementGuid>6200f28d-ecf5-4edb-8758-da2438776d51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
