<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Your Idea Created Successfully</name>
   <tag></tag>
   <elementGuidId>09d051cf-7b7a-48f3-bf6f-8aa7e6b484ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toastDescription557:0']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.toastMessage.forceActionsText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f795bcc7-6cde-4e5b-8847-77b0c7f1b5fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toastMessage forceActionsText</value>
      <webElementGuid>6d12066e-8c83-4244-9605-704ae92ab0ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>572:0</value>
      <webElementGuid>9444fca2-4705-4502-98ba-15aeb8f572b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-class</name>
      <type>Main</type>
      <value>forceActionsText</value>
      <webElementGuid>93d7911e-9f40-4ee1-b555-1719da3d0b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your Idea Created Successfully</value>
      <webElementGuid>067a77a3-5af1-4bb4-ac67-6f29b2f620cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toastDescription557:0&quot;)/span[@class=&quot;toastMessage forceActionsText&quot;]</value>
      <webElementGuid>1160c386-ef0e-4556-8e1c-33132adf371d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toastDescription557:0']/span</value>
      <webElementGuid>aeedbc79-08db-481d-ab90-4073c402b925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Success'])[2]/following::span[1]</value>
      <webElementGuid>6aee5fb5-26d0-4946-90b3-4c4aebfa8f49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Success'])[1]/following::span[1]</value>
      <webElementGuid>9bea8dcc-8f30-4dc6-bc63-2c8915d893a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::span[1]</value>
      <webElementGuid>ed765686-06a1-4c08-a464-7e0343f188a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading'])[2]/preceding::span[5]</value>
      <webElementGuid>67010fab-3031-4455-983b-b57ae9bbedb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your Idea Created Successfully']/parent::*</value>
      <webElementGuid>58db1512-07b9-4ed2-b03b-2dcdbf39c3df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div[2]/span</value>
      <webElementGuid>6627d1d2-269e-4645-833f-f6e06abb3dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Your Idea Created Successfully' or . = 'Your Idea Created Successfully')]</value>
      <webElementGuid>a039106c-b55e-4a94-a10c-0869aec65b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toastDescription847:0']/span</value>
      <webElementGuid>d8cfe156-5c5e-4028-a669-9ee261ffd24f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/span</value>
      <webElementGuid>489ae6fb-809b-4b88-b5fc-9ec51ee141fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
