<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Katalon Studio</name>
   <tag></tag>
   <elementGuidId>8935cca0-fcfd-46d8-853f-a259a0c5f37e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//lightning-base-combobox-item[@id='combobox-button-46-1-46']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#combobox-button-46-1-46 > span.slds-media__body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9ab42b80-d0fb-44f8-b32f-af6a50ba4e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-media__body</value>
      <webElementGuid>84f9e572-a6f7-4f9e-bd0a-86bfc3a25f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon Studio</value>
      <webElementGuid>7a2354c0-977b-4049-9c3a-a4a87ff9e0b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combobox-button-46-1-46&quot;)/span[@class=&quot;slds-media__body&quot;]</value>
      <webElementGuid>f3ab63e1-b804-4212-871a-487261d12383</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[@id='combobox-button-46-1-46']/span[2]</value>
      <webElementGuid>447400a6-a4ca-4106-ac1a-5dce4dbe40ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Product'])[1]/following::span[2]</value>
      <webElementGuid>6031746f-76b4-4029-8635-177ebeedeb7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::span[7]</value>
      <webElementGuid>27f01f01-8e2e-4b96-8f44-e8d28a4fe51a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cloud Studio'])[1]/preceding::span[3]</value>
      <webElementGuid>864802fc-8516-4eba-a5a4-f7a95f73a932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-base-combobox-item[2]/span[2]</value>
      <webElementGuid>da54c913-069e-45e6-af4c-5cbf86369ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Katalon Studio' or . = 'Katalon Studio')]</value>
      <webElementGuid>b56961ec-8f5f-4bd1-aca5-bd8169c003f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
